Repository cs2103-ay1819s2-w13-2/main, pull requests merged in 2019-04, with the labels that each got.

#182 updated userguide
  docs/UserGuide.adoc
Labels: severity.Low

#220 Updated User Guide and Corrected error
  docs/UserGuide.adoc
  docs/images/MemberList.png
  docs/team/A0143487X-Kevin.adoc
  docs/team/ivyyangyq.adoc
Labels: type.Bug

#236 MemberFilter bug fix and refactor
  src/main/java/seedu/address/logic/commands/MemberFilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCriteriaContainsKeywordPredicate.java
  src/main/java/seedu/address/logic/parser/MemberFilterCommandParser.java
  src/main/java/seedu/address/model/person/GenderContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/MajorContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/YearOfStudyContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MemberDetailPanel.java
  src/test/java/seedu/address/logic/parser/MemberFilterCommandParserTest.java
Labels: priority.High, type.Bug, type.Enhancement

#237 Documentation for PPP and Developer Guide (Ongoing)
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/MemberSortCommand_LogicComponentSequenceDiagram.pptx
  docs/images/MemberFilter_Logic.png
  docs/images/MemberFilter_Model.png
  docs/images/MemberSortCommand_LogicComponentSequenceDiagram.png
  docs/images/memberadd_validation.png
  docs/images/memberselect_sequence.png
  docs/images/person-attributes.png
  docs/images/updatedUIcomponent.png
  docs/team/joel0111.adoc
  src/main/java/seedu/address/logic/commands/MemberFilterCommand.java
Labels: status.Ongoing
