Repository cs2103-ay1819s2-w13-2/main, pull requests merged in 2019-03, with the labels that each got.

#102 Added Attributes to MemberAdd Command
  docs/UserGuide.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/address/logic/commands/MemberAddCommand.java
  src/main/java/seedu/address/logic/commands/MemberEditCommand.java
  src/main/java/seedu/address/logic/commands/MemberListCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MemberAddCommandParser.java
  src/main/java/seedu/address/logic/parser/MemberEditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/MatricNumber.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/YearOfStudy.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MemberAddCommandTest.java
  src/test/java/seedu/address/logic/commands/MemberEditCommandTest.java
  src/test/java/seedu/address/logic/commands/MemberEditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/MemberAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MemberEditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/MemberAddCommandSystemTest.java
  src/test/java/systemtests/MemberEditCommandSystemTest.java
Labels: priority.High

#107 Updated Sort command to sort by name, major, yearOfStudy, matricNumber
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/MemberAddCommand.java
  src/main/java/seedu/address/logic/parser/SortCriteriaContainsKeywordPredicate.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/MatricNumber.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/MemberAddCommandTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/MemberAddCommandSystemTest.java
  src/test/java/systemtests/MemberEditCommandSystemTest.java
Labels: type.Enhancement

#115 Updated MemberSort criteria and changed MatricNumber Validation Regex
  src/main/java/seedu/address/logic/parser/SortCriteriaContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/MatricNumber.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: type.Task

#126 memberFind enhancements
  src/test/java/seedu/address/logic/commands/MemberAddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement
